name: Build

on:
  push:
    branches-ignore: [gh-pages]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup test browser
        uses: browser-actions/setup-chrome@latest

      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'

      # TODO cache
      - name: Install
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint

      # TODO Run as separate job? Only when Install is cached
      - name: Test
        run: yarn test:ci

      - name: Cy Component Test
        run: yarn test:cy:ci

