name: Build

on:
  push:
    branches-ignore: [gh-pages]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup test browser
        uses: browser-actions/setup-chrome@latest

      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Cache
        id: install-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}

      - name: Install
        # if: steps.install-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test:ci

      - name: Cy Component Test
        run: yarn test:cy:ci

