name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Setup test browser
        uses: browser-actions/setup-chrome@latest

      - uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build --skip-nx-cache

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test:ci

      - run: cp README.md dist/gallery/

      - name: Release
        run: |
          cd dist/gallery
          npm publish --access public

  deploy-homepage:
    needs: release
    uses: daelmaak/ngx-gallery/.github/workflows/deploy-homepage.yml@master
